version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - default
    restart: always
    volumes:
      - ./www:/www
      - ./logs/nginx:/var/log/nginx:delegated
      - ./nginx_conf:/etc/nginx/conf.d:cached

  php-fpm:
    build:
      context: ./
      dockerfile: dockerfile.fpm
    ports:
      - "127.0.0.1:9000:9000"
    container_name: php-fpm
    restart: always
    networks:
      - default
    volumes:
      - ./www:/www
      - ./php_conf/profiler:/tmp/profiler:delegated
      - ./logs/php-fpm:/var/log:delegated
      - ./php_conf/php.ini:/usr/local/etc/php/php.ini:cached
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: serverName=mystream
      environment:
      FORCE_SSL: "false"
      XDEBUG_CONFIG: "client_host=172.17.0.1"
      # App environment
      APP_ENV: dev

  mysql:
    platform: linux/x86_64
    image: mysql:5.7.37
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mystream
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_conf:/etc/mysql/conf.d
    restart: always
    networks:
      - default
