controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# JWT-token generator
auth:
    path: /auth

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }